#ifndef pnEditorControlID_h__
#define pnEditorControlID_h__

enum
{
	ID_ASSEMBLE = wxID_HIGHEST,//menu id
	ID_DISSEMBLE,
	ID_BRING_TOP,
	ID_BRING_BOTTOM,
	ID_BRING_UP,
	ID_BRING_DOWN,
	ID_ALGINLEFT,
	ID_ALGINRIGHT,
	ID_ALGINHCENTER,
	ID_ALGINTOP,
	ID_ALGINBOTTOM,
	ID_ALGINVCENTER,
	ID_HSAMEDISTANCE,
	ID_VSAMEDISTANCE,
	ID_SAME_WIDTH,
	ID_SAME_HEIGHT,
	ID_SAME_SIZE,
	ID_ROTATE_N90,
	ID_ROTATE_P90,
	ID_FLIP_VERT,
	ID_FLIP_HORZ,
};

#endif // pnEditorControlID_h__
